<?php

use Illuminate\Database\Seeder;

class ArticlesTableSeeder extends Seeder
{
    public function run()
    {
        \DB::table('articles')->delete();
        
        \DB::table('articles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'home',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 0,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-07-04 06:54:35',
                'updated_at' => '2018-06-11 09:57:11',
            ),
            1 => 
            array (
                'id' => 2,
                'domain' => '',
                'parent_id' => NULL,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'company',
                'doc' => NULL,
                'image' => 'ff0000.png',
                'banner' => '',
                'link' => NULL,
                'sort' => 100,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 1,
                'template_id' => NULL,
                'created_by' => 0,
                'created_at' => '2016-07-04 06:56:59',
                'updated_at' => '2019-05-04 12:58:21',
            ),
            2 => 
            array (
                'id' => 3,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'privacy',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 2000,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-07-04 07:11:17',
                'updated_at' => '2017-08-01 14:33:01',
            ),
            3 => 
            array (
                'id' => 4,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'contacts',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 400,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 1,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-07-04 07:11:39',
                'updated_at' => '2017-08-01 14:32:40',
            ),
            4 => 
            array (
                'id' => 5,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'products',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 200,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 1,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-07-04 07:20:37',
                'updated_at' => '2018-01-25 11:03:49',
            ),
            5 => 
            array (
                'id' => 6,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'news',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 300,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 1,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-07-04 07:59:05',
                'updated_at' => '2017-08-01 14:33:11',
            ),
            6 => 
            array (
                'id' => 7,
                'domain' => '',
                'parent_id' => 9,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'login',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 1000,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-08-09 13:12:14',
                'updated_at' => '2017-08-01 15:57:18',
            ),
            7 => 
            array (
                'id' => 8,
                'domain' => '',
                'parent_id' => 9,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'user-dashboard',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 1200,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-08-09 13:24:04',
                'updated_at' => '2017-08-01 14:33:30',
            ),
            8 => 
            array (
                'id' => 9,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'reserved-area',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 1100,
                'pub' => 0,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-08-10 07:16:26',
                'updated_at' => '2017-08-01 15:57:05',
            ),
            9 => 
            array (
                'id' => 10,
                'domain' => '',
                'parent_id' => 9,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => 'user-profile',
                'doc' => '',
                'image' => '',
                'banner' => '',
                'link' => '',
                'sort' => 1300,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2016-08-10 07:17:38',
                'updated_at' => '2017-08-01 14:33:37',
            ),
            10 => 
            array (
                'id' => 11,
                'domain' => '',
                'parent_id' => 0,
                'menu_title' => NULL,
                'title' => '',
                'subtitle' => NULL,
                'intro' => NULL,
                'abstract' => NULL,
                'description' => '',
                'slug' => NULL,
                'doc' => NULL,
                'image' => NULL,
                'banner' => NULL,
                'link' => '',
                'sort' => 2000,
                'pub' => 1,
                'ignore_slug_translation' => 0,
                'top_menu' => 0,
                'template_id' => 0,
                'created_by' => 0,
                'created_at' => '2017-08-01 16:13:57',
                'updated_at' => '2017-08-01 16:16:28',
            ),
        ));
    }
}